set-option -g default-shell /bin/zsh

new-session -n $HOST

bind -t vi-copy y copy-pipe 'xclip -in -selection clipboard 2>&1 > /dev/null'
bind C-v run 'tmux set-buffer -- "$(xclip -o -selection clipboard -d :0.0)"; tmux paste-buffer'

